import type { Metadata } from "next";
import { Sulphur_Point } from "next/font/google";
import "./globals.css";

const sulphurPoint = Sulphur_Point({
  weight: ["300", "400", "700"],
  variable: "--font-sulphur-point-sans",
});

export const metadata: Metadata = {
  title: "Kadoo Edu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${sulphurPoint.variable} antialiased`}>{children}</body>
    </html>
  );
}
